# Site Settings
title: Nguyen Anh Tuan Resume
description: Curriculum Vitae of tuan@agiletech.vn
url: 'http://agiletech.vn'
baseurl: 'https://agiletechvn.github.io' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Nguyen Anh Tuan
tagline: Founder & Technical Manager
pic: https://github.com/anhtuank7c.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "I'm 30 years old Technical Manager of Agiletech Viet Nam and senior developer from the cozy street of Ha Noi. I have more than 7 years of work experience in various positions.
I love coding, music and swimming, football.
My visionary believed that teamwork is essential to delivering great software.
<br>
You can view more about <a href='http://agiletech.vn' target='_blank'>Agiletech Viet Nam</a>."

#sidebar links
email: tuan@agiletech.vn
phone: +84 98 280 8065
website: agiletech.vn #do not add http://
linkedin: nguyễn-anh-tuấn-49504952
github: anhtuank7c
twitter: '@anhtuank7c'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-119187154-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
